Traceback (most recent call last):
  File "/Users/jerryvelazquez/Dev/Python_Store/Coursera/course_2/Module_6/basic_CLI/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
